### ISSUE TITLE
Webcam streams gehen nicht

### ISSUE THREAD

**Issue by jomach** [bundesAPI/autobahn-api#17]
Ich teste gerade diese API. Bei Webcam bekommt man die Webcam link wie:  

{
  "webcam": [
    {
      "extent": "6.861151,50.987423,6.861151,50.987423",
      "identifier": "V0VCQ0FNX19OUldfU2lsYS1TaWduYWxiYXVfMTAxMDgxMDk4ODE2NDgyOTQ4NTQ=",
      "routeRecommendation": [],
      "coordinate": {
        "lat": "50.987423",
        "long": "6.861151"
      },
      "footer": [
        "ID: WEBCAM__NRW_Sila-Signalbau_10108109881648294854"
      ],
      "icon": "webcam",
      "isBlocked": "false",
      "description": [],
      "title": "A1 | ID005 AK Köln-Nord",
      "operator": "NRW",
      "point": "6.861151,50.987423",
      "display_type": "WEBCAM",
      "lorryParkingFeatureIcons": [],
      "future": false,
      "imageurl": "https://www.verkehr.nrw/webcams/10108109881648294854.jpg",
      "subtitle": "Blickrichtung Dortmund",
      "linkurl": "https://www.blitzvideoserver.de/player_strassennrw.html?serverip=62.113.210.7&serverapp=strassennrw-rtplive&streamname=10108109881648294854"
    }

der linkurl geht aber nicht. Weiß jemand wie ich auf dem Stream zugreifen kann ?

**Comment by wirthual** [comment]
Hi,

Die wurden vor einer Zeit Mal abgeschaltet:


Siehe  zum Beispiel [https://www.swr.de/swraktuell/baden-wuerttemberg/verkehrskameras-liefern-keine-bilder-mehr-100.html](hier).

**Comment by jomach** [comment]
Habe auch festgestellt das die api nur eine kamara liefert. Armutszeugnis für DE... 

Danke

**Comment by sbaum2s** [comment]
> Hi,
> 
> Die wurden vor einer Zeit Mal abgeschaltet:
> 
> Siehe zum Beispiel [hier](https://www.swr.de/swraktuell/baden-wuerttemberg/verkehrskameras-liefern-keine-bilder-mehr-100.html).

Die URL vom SWR geht auch nicht mehr

**Comment by sbaum2s** [comment]
> Habe auch festgestellt das die api nur eine kamara liefert. Armutszeugnis für DE...
> 
> Danke

Inzwischen gar keine mehr. Oder gibts noch eine API route, die überhaupt noch eine Liste der Webcams liefert? Ist die API eigentlich OpenSource oder muss man sich in die privaten Firmen hinter AutobahnOS einklinken, um sie zu verbessern?
