### ISSUE TITLE
Open API Dokumentation verlinken

### ISSUE THREAD

**Issue by benjaminknauer** [bundesAPI/autobahn-api#2]
Hier gibt es doch eine offizielle Open API Dokumentation der Schnittstellen.

https://autobahn.api.bund.dev/

Vielleicht in die Beschreibung aufnehmen?

**Comment by LilithWittmann** [comment]
@benjaminknauer das wird aus diesem Repository generiert. Ist Dir klar, oder?

**Comment by benjaminknauer** [comment]
Jetzt ja 🙈 Am Morgen kurz rumklicken und ranten, ohne richtig zu lesen ist scheinbar keine gute Idee. Super Projekt! Sowas müsste eigentlich von den Entwicklern bereitgestellt werden.
