### ISSUE TITLE
Bedeutung von icon

### ISSUE THREAD

**Issue by mvglasow** [bundesAPI/autobahn-api#22]
Das `icon`-Feld ist in den meisten Fällen eine dreistellige Zahl. Diese leitet sich grob aus den [offiziellen Nummern der Verkehrszeichen in der StVO](https://de.wikipedia.org/wiki/Bildtafel_der_Verkehrszeichen_in_der_Bundesrepublik_Deutschland_seit_2017) ab.

Allerdings gibt es auch Abweichungen: von der StVO abweichende Unternummern; Zeichen und Bedeutungen, die nur entfernt etwas mit der Bedeutung nach der StVO zu tun haben, oder nicht-numerische Werte, wo kein passendes Zeichen in der StVO existiert.

Insgesamt habe ich bislang beobachtet:

* `101`: Gefahr
* `123`: Bauarbeiten
* `250`: Sperrung
* `262-2`: Max. 3,5t (offizielles Zeichen wäre 262-3,5; die Unternummer gibt den Zahlenwert an)
* `314-50`: Park-/Rastplatz
* `448`: Anschlussstelle gesperrt (offiziell dient Zeichen 448 der Ankündigung einer Anschlussstelle auf Autobahnen)
* `charging_plug_strong`: Schnellladestation für E-Fahrzeuge
* `warnkegel`: Kurzzeitbaustelle

**Comment by mvglasow** [comment]
OpenAPI wird etwas schwierig – `Enum` möchte ich hier nicht verwenden, da ich nicht weiß, ob die Liste vollständig ist, und kenne mich in der Syntax nicht genügend aus, um Erklärungen zu Rückgabewerten unterzubringen.

Übrigens bin ich noch auf einen neuen Wert gestoßen: `314-50-2`: Park-/Rastplatz nur für Pkw

**Comment by t-huyeng** [comment]
Ich denke, das Ganze könnte auch in der Readme oder in der allgemeinen Beschreibung der OpenAPI für Anwender interessant sein. 

Für mich ist es auch in Ordnung, wenn wir hier im Issue noch ein wenig sammeln.

**Comment by mvglasow** [comment]
So, habe den Text als `description` an iconRef angehängt. Hoffe, Inline HTML ist OK. Wenn das eleganter geht, bin ich offen für Anregungen. Wer noch weitere `icon`-Werte findet, kann diese gern per PR ergänzen.

**Comment by mvglasow** [comment]
Nachdem der PR gemerged ist, schließe ich die Issue. Wer noch weitere Werte kennt, kann sie hier oder an anderer Stelle gern hinzufügen.
