### ISSUE TITLE
Keine Daten ab 01.01.2024?

### ISSUE THREAD

**Issue by podert** [bundesAPI/autobahn-api#40]
Kann es seien, dass "/{roadId}/services/warning" seid dem 01.01.2024 keine daten mehr ausgibt?
Kann das einer bestätigen?

**Comment by ReVoLt112** [comment]
Ja bekomme auch keine Warnungen mehr

**Comment by eyesfree** [comment]
Gibt es mittlerweile Warnungen für 2024?

**Comment by ReVoLt112** [comment]
Good News, bei mir seit gerade eben: Daten!

Keine Ahnung wer was gemacht hat, aber bei mir geht es jetzt.

**Comment by podert** [comment]
Danke für die Meldung.
Scheinbar wurden auch in paar kleine Änderungen gemacht... was mir so weit aufgefallen ist, dass bei den Warnungen nicht mehr "Pilsen Richtung Nürnberg" sondern jetzt "Pilsen -> Nürnberg" steht.

**Comment by lostVagabond81** [comment]
Eine andere Änderung betrifft die Filterung bei Sperrungen. Früher war es möglich die Vollsperrungen über die Property "display_type": "CLOSURE" zu bekommen. Das scheint nun nicht mehr möglich zu sein. Eventuell hilft die Property "isBlocked": "false" weiter, bin mir aber nicht sicher.

Kennt ihr eine Möglichkeit die Vollsperrungen zu selektieren? Sperrungen einer einzelnen Spur oder Ausfahrt interessieren mich weniger.
